# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 715c1e38415dcba9a06a0782a40dc343c3df8fb3386100c26c114d0285be7c23f916e0e07b72aa7babc45dc7af505b12f4800093dd05c5704886905c15d6a81f

test:
  secret_key_base: ce5199e922e18b51b853b72e3053bbd3eafd6e4203f70551b281f6acbfa3ca9494f0554a89a365fe3d6c4ba0d7eb2e72a0d293b78ea6bac4535fae15569e46c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
